# make_ablation_tex.R  (edu-revision)
# ------------------------------------------------------------------
# Writes the LaTeX macros and tables for the component (ablation) analysis,
# so that no number in latex/sections/results_rasch.tex is typed by hand.
# Run after the simulation scripts and analysis/rasch_offset_control.R and
# analysis/rasch_pfp2d_isolated.R, from the repository root:
#   Rscript analysis/make_ablation_tex.R
# Inputs : data/edu_revision/rasch_students.csv, rasch_ablation_students.csv,
#          rasch_pfp2d_iso_students.csv, rasch_offset_students.csv,
#          rasch_offset_meta.csv, r_offset_contrasts.csv, r_iso_contrasts.csv
# Outputs: latex/generated/ablation_numbers.tex, table_main.tex,
#          table_components.tex, table_alpha.tex
#
# Arm names used in the paper:
#   PFP-Core  = leaky staircase (Levitt, 1971) with restoring term; no fractal
#   PFP-Core+J = PFP-Core + 2-D step + jump rule (4 wrong -> X); no fractal
#   PFP-M1    = PFP-Core + alpha (1 - H)                     (1-D, alpha = 1)
#   PFP-M2    = PFP-Core+J + alpha ln((1 - H + eps)/(H + eps)) (2-D, alpha = 1)
#   Offset    = PFP-Core+J + constant shift equal to the mean PFP-M2 term
# ------------------------------------------------------------------
d   <- file.path("data", "edu_revision")
rd  <- function(f) read.csv(file.path(d, f), stringsAsFactors = FALSE)
st  <- rd("rasch_students.csv"); ab <- rd("rasch_ablation_students.csv")
iso <- rd("rasch_pfp2d_iso_students.csv"); off <- rd("rasch_offset_students.csv")
meta <- rd("rasch_offset_meta.csv"); coff <- rd("r_offset_contrasts.csv"); ciso <- rd("r_iso_contrasts.csv")
dir.create(file.path("latex", "generated"), showWarnings = FALSE, recursive = TRUE)

rn <- c(volkan = "One", difficulty = "Two")
metrics <- c(zpd = "Zpd", zpd_40_60 = "ZpdA", zpd_60_80 = "ZpdC", frustr = "Frustr", bored = "Bored",
             mean_p = "MeanP", gain = "Gain", track = "Track")
arm_data <- function(rule, arm) switch(arm,
  Saturn = st[st$rule == rule & st$arm == "Saturn", ], Factory = st[st$rule == rule & st$arm == "Factory", ],
  CAT = st[st$rule == rule & st$arm == "CAT", ], Core = st[st$rule == rule & st$arm == "PFP", ],
  CoreJ = off[off$rule == rule & off$arm == "2D_a0", ], MOne = ab[ab$rule == rule & ab$alpha == 1, ],
  MTwo = off[off$rule == rule & off$arm == "2D_a1", ], Offset = off[off$rule == rule & off$arm == "2D_offset", ])
arms <- c("Saturn", "Factory", "CAT", "Core", "CoreJ", "MOne", "MTwo", "Offset")

f3 <- function(x) sprintf("%.3f", x); sg <- function(x) sprintf("%+.3f", x)
L <- c("% Generated by analysis/make_ablation_tex.R -- do not edit by hand.")
def <- function(n, v) L <<- c(L, sprintf("\\newcommand{\\%s}{%s}", n, v))

# arm means
for (rule in names(rn)) for (a in arms) {
  x <- arm_data(rule, a)
  for (m in names(metrics)) def(paste0("m", a, metrics[[m]], rn[[rule]]), f3(mean(x[[m]])))
  if ("track_sd" %in% names(x)) def(paste0("m", a, "TrackSd", rn[[rule]]), f3(mean(x$track_sd)))
}
for (rule in names(rn)) def(paste0("offsetShift", rn[[rule]]), f3(meta$delta_b_static[meta$rule == rule]))

# contrasts with CI
cname <- c("2D_a1 - 2D_offset" = "MTwoVsOffset", "2D_offset - 2D_a0" = "OffsetVsCoreJ", "2D_a1 - 2D_a0" = "MTwoVsCoreJ")
mm2 <- c(metrics, track_sd = "TrackSd")
for (i in seq_len(nrow(coff))) {
  r <- coff[i, ]; if (!r$metric %in% names(mm2)) next
  b <- paste0("d", cname[[r$comparison]], mm2[[r$metric]], rn[[r$rule]])
  def(b, sg(r$diff)); def(paste0(b, "Lo"), sg(r$ci_low)); def(paste0(b, "Hi"), sg(r$ci_high))
  def(paste0(b, "Dz"), sprintf("%+.2f", r$d_z))
}
j <- ciso[ciso$arm == "2D_a0" & ciso$reference == "PFP", ]
for (i in seq_len(nrow(j))) {
  r <- j[i, ]; if (!r$metric %in% names(metrics)) next
  b <- paste0("dJump", metrics[[r$metric]], rn[[r$rule]])
  def(b, sg(r$diff)); def(paste0(b, "Lo"), sg(r$ci_low)); def(paste0(b, "Hi"), sg(r$ci_high))
}
# share of the frustration drop reproduced by the constant shift (Rule 1)
fr <- function(a) mean(arm_data("volkan", a)$frustr)
def("frustShareOffsetOne", sprintf("%.0f", 100 * (fr("CoreJ") - fr("Offset")) / (fr("CoreJ") - fr("MTwo"))))
writeLines(L, file.path("latex", "generated", "ablation_numbers.tex"))

# ---- Table: main results (6 arms) ----
lab <- c(Saturn = "Saturn", Factory = "Factory", CAT = "CAT ($P^\\ast{=}0.70$)", Core = "PFP-Core",
         MOne = "PFP-M1", MTwo = "PFP-M2")
rows <- c(zpd_40_60 = "Share $0.40 \\le P \\le 0.60$", zpd = "Share $0.50 \\le P \\le 0.70$ (pre-specified)",
          frustr = "Share $P < 0.30$", bored = "Share $P > 0.85$", gain = "Ability gain $\\theta_T-\\theta_0$",
          track = "Mean $|b_t-\\theta_t|$")
T1 <- c("% Generated by analysis/make_ablation_tex.R", "\\begin{tabular}{l l r r r r r r}", "\\toprule",
        paste0("Rule & Outcome & ", paste(lab, collapse = " & "), " \\\\"), "\\midrule")
for (rule in names(rn)) {
  first <- TRUE
  for (m in names(rows)) {
    v <- sapply(names(lab), function(a) f3(mean(arm_data(rule, a)[[m]])))
    T1 <- c(T1, paste0(if (first) c(volkan = "1: symmetric", difficulty = "2: difficulty-weighted")[[rule]] else "",
                       " & ", rows[[m]], " & ", paste(v, collapse = " & "), " \\\\")); first <- FALSE
  }
  if (rule == "volkan") T1 <- c(T1, "\\midrule")
}
T1 <- c(T1, "\\bottomrule", "\\end{tabular}")
writeLines(T1, file.path("latex", "generated", "table_main.tex"))

# ---- Table: component tests ----
getc <- function(tab, rule, comp, m) {
  if (comp == "Jump") { r <- ciso[ciso$rule == rule & ciso$arm == "2D_a0" & ciso$reference == "PFP" & ciso$metric == m, ] }
  else { r <- coff[coff$rule == rule & coff$comparison == comp & coff$metric == m, ] }
  if (nrow(r) == 0) return("--")
  sprintf("$%+.3f$ {\\scriptsize[%+.3f, %+.3f]}", r$diff, r$ci_low, r$ci_high)
}
comps <- c(Jump = "Jump rule (PFP-Core+J $-$ PFP-Core)",
           "2D_a1 - 2D_a0" = "Mandelbrot term, total (PFP-M2 $-$ PFP-Core+J)",
           "2D_offset - 2D_a0" = "Constant shift only (Offset $-$ PFP-Core+J)",
           "2D_a1 - 2D_offset" = "Beyond the shift (PFP-M2 $-$ Offset)")
cm <- c(gain = "Ability gain", frustr = "Share $P<0.30$", zpd_40_60 = "Share $0.40{-}0.60$", track_sd = "SD of $|b-\\theta|$")
T2 <- c("% Generated by analysis/make_ablation_tex.R", "\\begin{tabular}{l l r r r r}", "\\toprule",
        paste0("Rule & Contrast & ", paste(cm, collapse = " & "), " \\\\"), "\\midrule")
for (rule in names(rn)) {
  first <- TRUE
  for (k in names(comps)) {
    v <- sapply(names(cm), function(m) getc(NULL, rule, k, m))
    T2 <- c(T2, paste0(if (first) c(volkan = "1", difficulty = "2")[[rule]] else "", " & ", comps[[k]], " & ",
                       paste(v, collapse = " & "), " \\\\")); first <- FALSE
  }
  if (rule == "volkan") T2 <- c(T2, "\\midrule")
}
T2 <- c(T2, "\\bottomrule", "\\end{tabular}")
writeLines(T2, file.path("latex", "generated", "table_components.tex"))

# ---- Table: alpha sweep ----
alph <- c(0, 0.5, 1, 1.5)
T3 <- c("% Generated by analysis/make_ablation_tex.R", "\\begin{tabular}{l l l r r r r}", "\\toprule",
        "Model & Rule & Outcome & $\\alpha=0$ & $\\alpha=0.5$ & $\\alpha=1$ & $\\alpha=1.5$ \\\\", "\\midrule")
for (mod in c("PFP-M1", "PFP-M2")) for (rule in names(rn)) for (m in c("gain", "frustr", "zpd_40_60", "track")) {
  src <- if (mod == "PFP-M1") ab else iso
  v <- sapply(alph, function(a) f3(mean(src[src$rule == rule & src$alpha == a, m])))
  T3 <- c(T3, paste0(mod, " & ", rn[[rule]], " & ", rows[[m]], " & ", paste(v, collapse = " & "), " \\\\"))
}
T3 <- c(T3, "\\bottomrule", "\\end{tabular}")
T3 <- gsub(" & One & ", " & 1 & ", T3, fixed = TRUE); T3 <- gsub(" & Two & ", " & 2 & ", T3, fixed = TRUE)
writeLines(T3, file.path("latex", "generated", "table_alpha.tex"))
cat("written latex/generated/{ablation_numbers,table_main,table_components,table_alpha}.tex\n")
